version: 2
updates:
  # Enable version updates for npm/yarn for frontend
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `front` directory
    directory: "/front"
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "daily"

  # Enable version updates for npm/yarn for backend
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `back` directory
    directory: "/back"
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "daily"

  # Enable version updates for Docker
  - package-ecosystem: "docker"
    # Look for a `Dockerfile` in the `frontend` directory
    directory: "/front"
    # Check for updates once a week
    schedule:
      interval: "weekly"

  # Enable version updates for Docker
  - package-ecosystem: "docker"
    # Look for a `Dockerfile` in the `backend` directory
    directory: "/back"
    # Check for updates once a week
    schedule:
      interval: "weekly"