version: '3.3'
services:
    db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        ports:
            - 3306:3306
        environment:
            MYSQL_DATABASE: db
            MYSQL_ROOT_PASSWORD: example # This password is not secure, it is only for development and should be set through an environment file, non gitted
        volumes:
            - ./mysql/persist:/var/lib/mysql
            - ./mysql/init:/docker-entrypoint-initdb.d

    back:
        build: ./back/
        container_name: klannpuce-back
        ports:
            - 8000:8000
        volumes:
            - ./back:/usr/src/app
        depends_on:
            - db

    front:
        build: ./front/
        container_name: klannpuce-front
        ports:
            - 3000:3000
        volumes:
            - ./front:/usr/src/app
