version: "2.4"
services:
    back:
        build: ./back
        container_name: klannpuce-back
        ports:
            - 8000:8000
        volumes:
            - ./back:/usr/src/app
            - /usr/src/app/node_modules
    front:
        build: ./front/
        container_name: klannpuce-front
        ports:
            - 3000:3000
        volumes:
            - ./front:/usr/src/app
            - /usr/src/app/node_modules
