name: Checks for Frontend

on:
  pull_request:
    paths:
      - 'front/**'

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install modules and Lint code
        run: |
          cd front/
          yarn
          yarn lint
        env:
          CI: true
      - name: Test code
        run: |
          cd front/
          yarn test
        env:
          CI: true
      - name: Audit code
        run: |
          cd front/
          yarn audit
        env:
          CI: true
